### ISSUE TITLE
[Other] Adapt C&H test cluster to SCS Entropy (scs-0101)

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#416]
Adapt C&H test cluster to [SCS Entropy (scs-0101)](
https://docs-staging.scs.community/standards/scs-0101-v1-entropy) and evaluate its costs. 

Todos:

- [ ]  Adapt C&H test cluster to SCS standard 
- [x]  Update standard documentation with costs/cost estimation
- [x]  Write how to and/or adaption script

**Comment by cah-hbaum** [comment]
Cost estimation for this standard can be found [here](https://github.com/SovereignCloudStack/standards/blob/do-not-merge/scs-compliant-yaook/Informational/adaption-costs.md).

The how to and script can be found in [here](https://github.com/SovereignCloudStack/standards/blob/do-not-merge/scs-compliant-yaook/Informational/adaption-costs.md) and [here](https://github.com/SovereignCloudStack/standards/blob/do-not-merge/scs-compliant-yaook/Informational/setup.sh).

**Comment by cah-hbaum** [comment]
This standard can't be checked right now, since the virtualization of the Openstack cluster doesn't really allow for floating IPs to be assigned to a floating IP on the underlying provider network. This always results in connection problems with the VM used for tests. This can be seen in the output of the test script:
```
    ./iaas/entropy/entropy-check.py -c scs-test -d:
      rc: 1
      stdout: []
      stderr:
      - 'DEBUG: Connecting to cloud ''scs-test'''
      - 'DEBUG: Selected image: Debian 12 (26db03f8-e054-4724-bf6f-78ba995e22e8)'
      - 'DEBUG: Checking images and flavors for recommended attributes'
      - 'WARNING: Flavor ''SCS-1L-1'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-16V-32-100'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-8V-32'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-16V-32'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-4V-8-20'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-8V-32-100'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-4V-32-100'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-1V-2-5'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-2V-4'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-2V-8-20'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-8V-16'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-1V-4-10'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-1V-2'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-4V-16-100s'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-2V-16'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-2V-4-20s'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-4V-8'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-8V-16-50'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-1V-8'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-4V-32'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-1V-8-20'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-4V-16-50'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-2V-8'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-1V-4'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-1L-1-5'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-2V-4-10'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-4V-16'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'WARNING: Flavor ''SCS-2V-16-50'' missing recommended attributes: hw_rng:allowed=True;
        additionally, missing optional attributes: hw_rng:rate_bytes, hw_rng:rate_period'
      - 'DEBUG: Checking dynamic instance properties'
      - 'DEBUG: Using external network 9ab58a3a-433e-4b76-961f-61f18c7cf916.'
      - 'DEBUG: Unable to pick flavor with hw_rng:allowed=true for image ''Debian
        12'''
      - 'DEBUG: Creating instance of image ''Debian 12'' using flavor ''SCS-1V-4-10'''
      - 'DEBUG: Deleting server ''_scs-0101-server'''
      - 'CRITICAL: SDKException(''Error in creating the server (no further information
        available)'')'
      - 'DEBUG: Exception info'
      - 'Traceback (most recent call last):'
      - '  File "/standards/Tests/iaas/entropy/entropy-check.py", line 453, in main'
      - '    server = create_vm(env, all_flavors, image)'
      - '  File "/standards/Tests/iaas/entropy/entropy-check.py", line 327, in create_vm'
      - '    server = env.conn.create_server('
      - '  File "/.scs-venv-test/lib/python3.9/site-packages/decorator.py", line 232,
        in fun'
      - '    return caller(func, *(extras + args), **kw)'
      - '  File "/.scs-venv-test/lib/python3.9/site-packages/openstack/cloud/_utils.py",
        line 224, in func_wrapper'
      - '    return func(*args, **kwargs)'
      - '  File "/.scs-venv-test/lib/python3.9/site-packages/openstack/cloud/_compute.py",
        line 993, in create_server'
      - '    server = self.wait_for_server('
      - '  File "/.scs-venv-test/lib/python3.9/site-packages/openstack/cloud/_compute.py",
        line 1143, in wait_for_server'
      - '    server = self.get_active_server('
      - '  File "/.scs-venv-test/lib/python3.9/site-packages/openstack/cloud/_compute.py",
        line 1182, in get_active_server'
      - '    raise exceptions.SDKException('
      - 'openstack.exceptions.SDKException: Error in creating the server (no further
        information available)'
      - 'DEBUG: Total critical / error / warning: 1 / 0 / 28'
      info: 0
      warning: 28
      error: 0
      critical: 1
      result: 0
```
This specifically has problems with the server creation, but the underlying problem remains the same.

**Comment by cah-hbaum** [comment]
I'm gonna close this issue now as "Won't do".
Its probably possible to test this on "f1a" cluster, but the time it would take isn't worth it and since we already we're able to confirm this working on our productive cluster, I think we can live with that.
