### ISSUE TITLE
[BUG] compliance job must produce yaml file when critical errors are encountered

### ISSUE THREAD

**Issue by mbuechse** [SovereignCloudStack/standards#459]
- Critiical errors are reported as failure to Zuul
- Then, the artifact (the YAML report) doesn't get stored

Also, the YAML file could be more verbose to make debugging the errors easier.

**Comment by mbuechse** [comment]
Regarding the apt-get problem:

Console output when the installation fails:
```console
apt 2.4.11 (amd64)
Supported modules:
*Ver: Standard .deb
 Pkg:  Debian APT solver interface (Priority -1000)
 Pkg:  Debian APT planner interface (Priority -1000)
*Pkg:  Debian dpkg interface (Priority 30)
 S.L: 'deb' Debian binary tree
 S.L: 'deb-src' Debian source tree
 Idx: EDSP scenario file
 Idx: EIPP scenario file
 Idx: Debian Source Index
 Idx: Debian Package Index
 Idx: Debian Translation Index
 Idx: Debian dpkg status file
 Idx: Debian deb file
 Idx: Debian dsc file
 Idx: Debian control file
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1395 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main Translation-en [510 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [129 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/restricted Translation-en [18.6 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [14.1 MB]
Get:10 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1109 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/universe Translation-en [5652 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [217 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy/multiverse Translation-en [112 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/main Translation-en [207 kB]
Get:15 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1313 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1326 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/restricted Translation-en [214 kB]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [837 kB]
Get:19 http://security.ubuntu.com/ubuntu jammy-security/universe Translation-en [160 kB]
Get:20 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [37.1 kB]
Get:21 http://security.ubuntu.com/ubuntu jammy-security/multiverse Translation-en [7476 B]
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [268 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1342 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [220 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1042 kB]
Get:26 http://archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [235 kB]
Get:27 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [42.1 kB]
Get:28 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse Translation-en [10.1 kB]
Get:29 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [41.7 kB]
Get:30 http://archive.ubuntu.com/ubuntu jammy-backports/main Translation-en [10.5 kB]
Get:31 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [24.2 kB]
Get:32 http://archive.ubuntu.com/ubuntu jammy-backports/universe Translation-en [16.5 kB]
Fetched 31.2 MB in 5s (6550 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package rng-tools5
```

Console output when it succeeds:
```console
apt 2.4.11 (amd64)
Supported modules:
*Ver: Standard .deb
 Pkg:  Debian APT solver interface (Priority -1000)
 Pkg:  Debian APT planner interface (Priority -1000)
*Pkg:  Debian dpkg interface (Priority 30)
 S.L: 'deb' Debian binary tree
 S.L: 'deb-src' Debian source tree
 Idx: EDSP scenario file
 Idx: EIPP scenario file
 Idx: Debian Source Index
 Idx: Debian Package Index
 Idx: Debian Translation Index
 Idx: Debian dpkg status file
 Idx: Debian deb file
 Idx: Debian dsc file
 Idx: Debian control file
Get:1 http://az1.clouds.archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:2 http://az1.clouds.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:3 http://az1.clouds.archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:5 http://az1.clouds.archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1395 kB]
Get:6 http://az1.clouds.archive.ubuntu.com/ubuntu jammy/main Translation-en [510 kB]
Get:7 http://az1.clouds.archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [129 kB]
Get:8 http://az1.clouds.archive.ubuntu.com/ubuntu jammy/restricted Translation-en [18.6 kB]
Get:9 http://az1.clouds.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [14.1 MB]
Get:10 http://az1.clouds.archive.ubuntu.com/ubuntu jammy/universe Translation-en [5652 kB]
Get:11 http://az1.clouds.archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [217 kB]
Get:12 http://az1.clouds.archive.ubuntu.com/ubuntu jammy/multiverse Translation-en [112 kB]
Get:13 http://az1.clouds.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1326 kB]
Get:14 http://az1.clouds.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [268 kB]
Get:15 http://az1.clouds.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1342 kB]
Get:16 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1109 kB]
Get:17 http://az1.clouds.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [220 kB]
Get:18 http://az1.clouds.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1042 kB]
Get:19 http://az1.clouds.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [235 kB]
Get:20 http://az1.clouds.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [42.1 kB]
Get:21 http://az1.clouds.archive.ubuntu.com/ubuntu jammy-updates/multiverse Translation-en [10.1 kB]
Get:22 http://az1.clouds.archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [41.7 kB]
Get:23 http://az1.clouds.archive.ubuntu.com/ubuntu jammy-backports/main Translation-en [10.5 kB]
Get:24 http://az1.clouds.archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [24.2 kB]
Get:25 http://az1.clouds.archive.ubuntu.com/ubuntu jammy-backports/universe Translation-en [16.5 kB]
Get:26 http://security.ubuntu.com/ubuntu jammy-security/main Translation-en [207 kB]
Get:27 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1313 kB]
Get:28 http://security.ubuntu.com/ubuntu jammy-security/restricted Translation-en [214 kB]
Get:29 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [837 kB]
Get:30 http://security.ubuntu.com/ubuntu jammy-security/universe Translation-en [160 kB]
Get:31 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [37.1 kB]
Get:32 http://security.ubuntu.com/ubuntu jammy-security/multiverse Translation-en [7476 B]
Fetched 31.2 MB in 4s (7809 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  rng-tools5
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 20.0 kB of archives.
After this operation, 84.0 kB of additional disk space will be used.
Get:1 http://az1.clouds.archive.ubuntu.com/ubuntu jammy/universe amd64 rng-tools5 amd64 5-4 [20.0 kB]
Fetched 20.0 kB in 0s (63.8 kB/s)
Selecting previously unselected package rng-tools5.
(Reading database ... 42163 files and directories currently installed.)
Preparing to unpack .../rng-tools5_5-4_amd64.deb ...
Unpacking rng-tools5 (5-4) ...
Setting up rng-tools5 (5-4) ...
Created symlink /etc/systemd/system/multi-user.target.wants/rngd.service → /lib/systemd/system/rngd.service.

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.
```

**Comment by mbuechse** [comment]
The package clearly exists: <https://packages.ubuntu.com/search?keywords=rng-tools5>
And in both instances, the same sources seem to be fetched!
**NO**, in fact, the URLs do differ. In the failing case, the URLs start with `http://archive.ubuntu.com`. How is this possible, when the same VM image (namely, _Ubuntu Minimal 22.04_) is used in both cases?
@frosty-geek How can this be?

**Comment by mbuechse** [comment]
Regarding the key-selection problem:

Debug output when it works:

```console
DEBUG: starting thread (client mode): 0x4aff09a0
DEBUG: Local version/idstring: SSH-2.0-paramiko_2.9.3
DEBUG: Remote version/idstring: SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.6
INFO: Connected (version 2.0, client OpenSSH_8.9p1)
DEBUG: === Key exchange possibilities ===
DEBUG: kex algos: curve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, sntrup761x25519-sha512@openssh.com, diffie-hellman-group-exchange-sha256, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, diffie-hellman-group14-sha256, kex-strict-s-v00@openssh.com
DEBUG: server key: rsa-sha2-512, rsa-sha2-256, ecdsa-sha2-nistp256, ssh-ed25519
DEBUG: client encrypt: chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com
DEBUG: server encrypt: chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com
DEBUG: client mac: umac-64-etm@openssh.com, umac-128-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64@openssh.com, umac-128@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1
DEBUG: server mac: umac-64-etm@openssh.com, umac-128-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64@openssh.com, umac-128@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1
DEBUG: client compress: none, zlib@openssh.com
DEBUG: server compress: none, zlib@openssh.com
DEBUG: client lang: <none>
DEBUG: server lang: <none>
DEBUG: kex follows: False
DEBUG: === Key exchange agreements ===
DEBUG: Strict kex mode: True
DEBUG: Kex: curve25519-sha256@libssh.org
DEBUG: HostKey: ssh-ed25519
DEBUG: Cipher: aes128-ctr
DEBUG: MAC: hmac-sha2-256
DEBUG: Compression: none
DEBUG: === End of kex handshake ===
DEBUG: Resetting outbound seqno after NEWKEYS due to strict mode
DEBUG: kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEBUG: Switch to new keys ...
DEBUG: Resetting inbound seqno after NEWKEYS due to strict mode
DEBUG: Adding ssh-ed25519 host key for 78.138.68.46: b'760cd95971fbc5df60d6bab0e84d1aba'
DEBUG: Got EXT_INFO: {'server-sig-algs': b'ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com', 'publickey-hostbound@openssh.com': b'0'}
DEBUG: Trying discovered key b'c095cbcc82b2229191de5fa059d387c9' in /tmp/tmp05mna52d
DEBUG: userauth is OK
DEBUG: Finalizing pubkey algorithm for key of type 'ssh-rsa'
DEBUG: Our pubkey algorithm list: ['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa']
DEBUG: Server-side algorithm list: ['ssh-ed25519', 'sk-ssh-ed25519@openssh.com', 'ssh-rsa', 'rsa-sha2-256', 'rsa-sha2-512', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', 'ecdsa-sha2-nistp521', 'sk-ecdsa-sha2-nistp256@openssh.com', 'webauthn-sk-ecdsa-sha2-nistp256@openssh.com']
DEBUG: Agreed upon 'rsa-sha2-512' pubkey algorithm
INFO: Authentication (publickey) successful!
```

Debug output when it fails:
```console
DEBUG: starting thread (client mode): 0x4cab3790
DEBUG: Local version/idstring: SSH-2.0-paramiko_2.9.3
DEBUG: Remote version/idstring: SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.6
INFO: Connected (version 2.0, client OpenSSH_8.9p1)
DEBUG: === Key exchange possibilities ===
DEBUG: kex algos: curve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, sntrup761x25519-sha512@openssh.com, diffie-hellman-group-exchange-sha256, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, diffie-hellman-group14-sha256, kex-strict-s-v00@openssh.com
DEBUG: server key: rsa-sha2-512, rsa-sha2-256, ecdsa-sha2-nistp256, ssh-ed25519
DEBUG: client encrypt: chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com
DEBUG: server encrypt: chacha20-poly1305@openssh.com, aes128-ctr, aes192-ctr, aes256-ctr, aes128-gcm@openssh.com, aes256-gcm@openssh.com
DEBUG: client mac: umac-64-etm@openssh.com, umac-128-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64@openssh.com, umac-128@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1
DEBUG: server mac: umac-64-etm@openssh.com, umac-128-etm@openssh.com, hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64@openssh.com, umac-128@openssh.com, hmac-sha2-256, hmac-sha2-512, hmac-sha1
DEBUG: client compress: none, zlib@openssh.com
DEBUG: server compress: none, zlib@openssh.com
DEBUG: client lang: <none>
DEBUG: server lang: <none>
DEBUG: kex follows: False
DEBUG: === Key exchange agreements ===
DEBUG: Strict kex mode: True
DEBUG: Kex: curve25519-sha256@libssh.org
DEBUG: HostKey: ssh-ed25519
DEBUG: Cipher: aes128-ctr
DEBUG: MAC: hmac-sha2-256
DEBUG: Compression: none
DEBUG: === End of kex handshake ===
DEBUG: Resetting outbound seqno after NEWKEYS due to strict mode
DEBUG: kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
DEBUG: Switch to new keys ...
DEBUG: Resetting inbound seqno after NEWKEYS due to strict mode
DEBUG: Adding ssh-ed25519 host key for 78.138.68.80: b'7ebae63a5086f2be32e19dd1fd9c35c1'
DEBUG: Got EXT_INFO: {'server-sig-algs': b'ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,webauthn-sk-ecdsa-sha2-nistp256@openssh.com', 'publickey-hostbound@openssh.com': b'0'}
DEBUG: Trying discovered key b'f31b8623402b0f81a2049fbad2d28eed' in /tmp/tmp43pn4mzv
DEBUG: userauth is OK
DEBUG: Finalizing pubkey algorithm for key of type 'ssh-rsa'
DEBUG: Our pubkey algorithm list: ['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa']
DEBUG: Server-side algorithm list: ['ssh-ed25519', 'sk-ssh-ed25519@openssh.com', 'ssh-rsa', 'rsa-sha2-256', 'rsa-sha2-512', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', 'ecdsa-sha2-nistp521', 'sk-ecdsa-sha2-nistp256@openssh.com', 'webauthn-sk-ecdsa-sha2-nistp256@openssh.com']
DEBUG: Agreed upon 'rsa-sha2-512' pubkey algorithm
INFO: Authentication (publickey) failed.
DEBUG: Trying SSH agent key b'ebf9b5346bd01695b9c29397f443841b'
DEBUG: userauth is OK
ERROR: Exception (client): key cannot be used for signing
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/lib/python3/dist-packages/paramiko/transport.py", line 2212, in run
ERROR:     handler(self.auth_handler, m)
ERROR:   File "/usr/lib/python3/dist-packages/paramiko/auth_handler.py", line 377, in _parse_service_accept
ERROR:     sig = self.private_key.sign_ssh_data(blob, algorithm)
ERROR:   File "/usr/lib/python3/dist-packages/paramiko/agent.py", line 434, in sign_ssh_data
ERROR:     raise SSHException("key cannot be used for signing")
ERROR: paramiko.ssh_exception.SSHException: key cannot be used for signing
ERROR: 
DEBUG: Trying SSH agent key b'198bd7d9809727b7a787871f1102b34b'
```

For some obscure reason, the initial key doesn't work here, and then paramiko goes on to use keys from the SSH agent (which is not good).

**Comment by frosty-geek** [comment]
@mbuechse I have no real good explanation why this is happening, but I've run into a similar problem in the past which I have mitigated by explicitly using the plusserver ubuntu mirror via cloud-init

see the apt primary section in this gist https://gist.github.com/frosty-geek/d2d56373d3ba415207b9977ef744e095

**Comment by mbuechse** [comment]
@frosty-geek Thanks, that helped a great deal! I had to add `cloud-init status --long --wait` before the `apt` stuff so the cloud-init changes could take effect.
