### ISSUE TITLE
[BUG] entropy-check taking hours

### ISSUE THREAD

**Issue by mbuechse** [SovereignCloudStack/standards#696]
This happens on the syseleven environments. The test is terminated by Github after 6 hrs when it reaches the maximum runtime...

**Comment by mbuechse** [comment]
There seems to be a problem with installing the Debian packages. Quoting [this run](https://github.com/SovereignCloudStack/standards/actions/runs/10381421137/job/28742808078):

```console
Socket exception: Connection reset by peer (104)
DEBUG: Error running 'apt-get':

apt 1.4.11 (amd64)
Supported modules:
*Ver: Standard .deb
*Pkg:  Debian dpkg interface (Priority 30)
 Pkg:  Debian APT solver interface (Priority -1000)
 Pkg:  Debian APT planner interface (Priority -1000)
 S.L: 'deb' Debian binary tree
 S.L: 'deb-src' Debian source tree
 Idx: Debian Source Index
 Idx: Debian Package Index
 Idx: Debian Translation Index
 Idx: Debian dpkg status file
 Idx: Debian deb file
 Idx: Debian dsc file
 Idx: Debian control file
 Idx: EDSP scenario file
 Idx: EIPP scenario file
## Note, this file is written by cloud-init on first boot of an instance
## modifications made here will not survive a re-bundle.
## if you wish to make changes you can:
## a.) add 'apt_preserve_sources_list: true' to /etc/cloud/cloud.cfg
##     or do the same in user-data
## b.) add sources in /etc/apt/sources.list.d
## c.) make changes to template file /etc/cloud/templates/sources.list.debian.tmpl
###

# See http://www.debian.org/releases/stable/i386/release-notes/ch-upgrading.html
# for how to upgrade to newer versions of the distribution.
deb https://mirror.plusserver.com/debian/debian/ stretch main contrib non-free
deb-src https://mirror.plusserver.com/debian/debian/ stretch main contrib non-free

## Major bug fix updates produced after the final release of the
## distribution.
deb https://mirror.plusserver.com/debian/debian/ stretch/updates main contrib non-free
deb-src https://mirror.plusserver.com/debian/debian/ stretch/updates main contrib non-free
deb https://mirror.plusserver.com/debian/debian/ stretch-updates main contrib non-free
deb-src https://mirror.plusserver.com/debian/debian/ stretch-updates main contrib non-free

## Uncomment the following two lines to add software from the 'backports'
## repository.
## 
## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
# deb https://mirror.plusserver.com/debian/debian/ stretch-backports main contrib non-free
# deb-src https://mirror.plusserver.com/debian/debian/ stretch-backports main contrib non-free
CRITICAL: Couldn't check VM 'Debian Stretch' requirements
Traceback (most recent call last):
  File "/scs-compliance/iaas/entropy/entropy-check.py", line 144, in check_vm_requirements
    install_test_requirements(fconn)
  File "/scs-compliance/iaas/entropy/entropy-check.py", line 126, in install_test_requirements
    _ = fconn.run(cmd, hide=True)
  File "/usr/local/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.10/site-packages/fabric/connection.py", line 22, in opens
    self.open()
  File "/usr/local/lib/python3.10/site-packages/fabric/connection.py", line 665, in open
    result = self.client.connect(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: [Errno 110] Connection timed out
```

I can't really tell where the first line comes from (the Socket exception). It may be possible that it comes from this:

```python
    _ = fconn.run('cloud-init status --long --wait', hide=True, warn=True)
```

where cloud config is

```text
#cloud-config
apt:
  primary:
    - arches: [default]
      uri: https://mirror.plusserver.com/debian/debian/
  security: []
```

The next lines after the first one do show that this mirror has indeed been put in the apt config (sources.list), so the cloud-init works regardless of the socket problem. However, apt itself doesn't seem to work this way.

I'm wondering if there's a problem between syseleven and plusserver? I think the mirrors do usually work with other environments.

**Comment by mbuechse** [comment]
Now, I'm testing locally with some more debug output. First of all, what I see is this:

```text
usage: cloud-init [-h] [--version] [--file FILES] [--debug] [--force]
                  {init,modules,query,single,dhclient-hook} ...
cloud-init: error: invalid choice: 'status' (choose from 'init', 'modules', 'query', 'single', 'dhclient-hook')
```

This is unfortunate. Why is the status command not available? Okay, Debian Stretch is like totally outdated... Why are we using Debian Stretch? I have to improve on image selection...

**Comment by mbuechse** [comment]
It turns out that using a more recent version than Stretch already solves the problem :facepalm:
